### ISSUE TITLE
Predict.py

### ISSUE THREAD

**Issue by numanai** [FirasBaba/rsna-resnet10#1]
Hi!

Thanks for sharing the project code. 

I don't see any code in the predict.py file other than package imports; this is on purpose?

Thanks

**Comment by FirasBaba** [comment]
@numanai Sorry. You are right. I have uploaded the wrong file and I didn't notice it. I will update it as soon as possible.

**Comment by Elliot-QxZhang** [comment]
hi, have you uploaded the correct file?

**Comment by maitanha** [comment]
Hi FirasBaba

It seems the predict.py still misses code, just package imports.
Can you take a look, please?
Thanks

**Comment by FirasBaba** [comment]
Hi all, 
Sorry for the very late response. The code now is updated.
Thank you
