### ISSUE TITLE
question about train_valid.sh

### ISSUE THREAD

**Issue by Elliot-QxZhang** [FirasBaba/rsna-resnet10#2]
I think maybe you miss ".py" for every file name in train_valid.sh.

Original Code:

python3 create_folds --n_folds 5

python3 -m train --fold 0 --type T1wCE --model_name resnet10
python3 -m train --fold 1 --type T1wCE --model_name resnet10
python3 -m train --fold 2 --type T1wCE --model_name resnet10
python3 -m train --fold 3 --type T1wCE --model_name resnet10
python3 -m train --fold 4 --type T1wCE --model_name resnet10

python3 -m validation

**Comment by FirasBaba** [comment]
`python train.py`: runs the script `train.py` as the main program.
`python -m train`: Treats the module named `train` as the main program and executes it. This is very useful for running modules in packages.

It is fine to run it using both methods:
python3 train.py --fold 0 --type T1wCE --model_name resnet10
python3 -m train --fold 0 --type T1wCE --model_name resnet10
